name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  HUSKY: 0
  TURBO_TELEMETRY_DISABLED: 1
jobs:
  application-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: ./.turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: Install npm packages
        id: npm-ci
        run: npm ci --no-fund
      - name: Check Formatting
        id: fmt
        run: npx turbo format:ci
      - name: Lint
        id: lint
        run: npx turbo lint:ci
      - name: Run Unit Tests
        id: test
        run: npx turbo test
      - name: License Scan
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          scanners: 'license'
          severity: 'MEDIUM,HIGH,CRITICAL'
  documentation-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'
          config: '.config/.markdownlint-cli2.jsonc'
